owner: ub-unibe-ch
repo: ub-public-services-status

sites:
  - name: Agenda
    url: https://agenda.ub.unibe.ch/
  - name: Berner Ortsgeschichten
    url: https://berner-ortsgeschichten.ub.unibe.ch/
  - name: BERNHIST
    url: https://bernhist.ch/
  - name: Biblio (File Download)
    url: https://biblio.unibe.ch/
  - name: Billing
    url: https://billing.ub.unibe.ch/
  - name: Collection Ryhiner
    url: https://ryhiner.ub.unibe.ch/
  - name: DigiBern
    url: https://digibern.ch/
  - name: IIIF Server
    url: https://iiif.ub.unibe.ch/
  - name: Literapedia Bern
    url: https://literapedia-bern.ch/
  - name: MetaEQ
    url: https://metaeq.ub.unibe.ch/
    expectedStatusCodes:
      - 400
  - name: PHBern Teacher
    url:  https://phbern-teacher.ub.unibe.ch/
    expectedStatusCodes:
      - 400
  - name: Research Databases
    url: https://databases.ub.unibe.ch/
  - name: Room Reservation
    url: https://raumreservation.ub.unibe.ch/
  - name: URN Resolver
    url: https://urn.ub.unibe.ch/
    expectedStatusCodes:
      - 404
  - name: ZMS Publication List
    url: https://publicationlist.ub.unibe.ch/

status-website:
  theme: light
  themeUrl: https://ub-unibe-ch.github.io/ub-public-services-status/unibe-theme.css
  logoUrl: https://ub-unibe-ch.github.io/ub-public-services-status/logo.png
  baseUrl: /ub-public-services-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: University Library Public Applications
  introTitle: "**Uptime monitor and status page for the public reachable applications of the University Library of Bern**"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/$OWNER/$REPO).
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
